[sdl]
fullscreen=false
autolock=true

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cycles=auto

[mixer]
rate=44100

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[autoexec]
@echo off
mount c game
c:
GAME.COM
exit
