[sdl]
fullscreen=false

[dosbox]
machine=svga_s3
memsize=16
automount=false

[render]
glshader=none

[cpu]
core=dynamic
cpu_cycles=max

[speaker]
pcspeaker=impulse
tandy=off

[mixer]
rate=44100

[sblaster]
sbtype=none

[midi]
mpu401=none
mididevice=none

[ethernet]
ne2000=false

[voodoo]
voodoo=false

[autoexec]
@echo off
mount c game
c:
GAME.COM
exit
